### ISSUE TITLE
폴더 구조 및 파일명에 관하여

### ISSUE THREAD

**Issue by jariita** [woowacourse-study/2023-effective-typescript-study#2]
### 폴더 구조

![현재폴더구조](https://user-images.githubusercontent.com/87710730/232228656-47212408-4266-4084-b609-72c314e6238b.png)

item25와 item26 폴더가 Chapter와 관계없이 밖으로 나와있어요.

> ✍️ [수정] - Chapter3 폴더를 만들어 Item을 옮길 것을 요청합니다.

### 아이템 순서

![아이템순서](https://user-images.githubusercontent.com/87710730/232229015-02dc97df-c691-46ec-ba67-25de3c6ee9a4.png)

item7, 8, 9가 아래로 내려가있어요.

> ✍️ [수정] - prefix를 추가할 것을 요청합니다. (`Item07, Item08, Item09`)

### Study Review

Study Review 안에 제로의 회고 `1-3주차 회고.md` 하나만 있어요.

> ✉️ [건의] - 이를 `1-3주차 회고` 폴더와 각자의 파일로 변경할 것을 건의합니다.

### 파일명

현재 본명을 사용하여 파일명을 구성하고 있어요.

> ✉️ [건의] - 현재 `이름.md`로 하고 있는데 `닉네임(이름).md`로 변경할 것을 건의합니다.

## 제안

✍️ [수정] - Chapter3 폴더를 만들어 Item을 옮길 것을 요청합니다.
✍️ [수정] - prefix를 추가할 것을 요청합니다. (`Item07, Item08, Item09`)
✉️ [건의] - 이를 `1-3주차 회고` 폴더와 각자의 파일로 변경할 것을 건의합니다.
✉️ [건의] - 현재 `이름.md`로 하고 있는데 `닉네임(이름).md`로 변경할 것을 건의합니다.

위 4가지 사항을 반영한 구조는 아래와 같습니다.
각 사항을 읽어보고 의견 부탁드려요!

```bash
├── Chapter2
│   ├── Item07
│   │   └── 제로(강인영).md
│   ├── Item08
│   │   └── 제로(강인영).md
│   ├── Item09
│   │   └── 제로(강인영).md
│   ├── Item10
│   │   └── 제로(강인영).md
│   ...
├── Chapter3
│   ├── Item25
│   │   └── 루루(송지은).md
│   ├── Item26
│   │   └── 루루(송지은).md
├── README.md
└── Study Review
    └── 1-3주차 회고
        └── 제로(강인영).md
```

**Comment by inyeong-kang** [comment]
제안 감사합니다 코난~ 말씀하신 방식으로 수정 완료했어요!🙂
수정 잘됐는지 확인 부탁드릴게요!
